### ISSUE TITLE
Templatize official rules

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#192] opened 2016-04-08 20:09 UTC
Official rules need to be set up per competition (really per waiting room split - all competitions that are born out of one waiting room split would share official rules information).

Once we have a set template for this we'll need:

- to make sure admins are setting necessary values
- to come up with a way to include official rules in the `reminder for first submission due` email

**Comment by angaither** [comment] 2016-04-25 13:22
duplicate of #243

**Closed by angaither** 2016-04-25 13:22 UTC
