### ISSUE TITLE
Create top 3 reportbacks "variable"

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#147] opened 2016-03-28 16:17 UTC
As an admin, I want to automatically pull the top 3 (by quantity) reportback images into the email

- pull in the most recent reportback photo
 - it must have already been approved
- include the `first name` `quantity` `photo caption`

**Comment by sbsmith86** [comment] 2016-04-11 23:17
This looks like a dupe of #195 which I created and assigned to myself. I was gonna hop on pulling in top three reportbacks while the leaderboard optimization work was being done.

@mikefantini @deadlybutter ok if I just move forward with this one?

**Comment by mikefantini** [comment] 2016-04-11 23:32
@sbsmith86 go for it!

**Comment by sbsmith86** [comment] 2016-04-12 16:28
Closing out. work on this is being done in #195

**Closed by sbsmith86** 2016-04-12 16:28 UTC
Labels: #leaderboard, #messaging, priority-high
